### ISSUE TITLE
Reference to non existent example

### ISSUE THREAD

**Issue by mgrojo** [JeremyGrosser/tiny_text#2]
https://github.com/JeremyGrosser/tiny_text/blob/93867cdeebc3958298afc649b88619c716b2e108/README.md?plain=1#L9

**Comment by JeremyGrosser** [comment]
Thanks for pointing this out. I'm not sure what happened to the old example, but I'll work on a new one.

**Comment by JeremyGrosser** [comment]
New examples in commit fc600fabe548cc6c7c5b9a574c1ac764e3bfe8ea.

**Comment by mgrojo** [comment]
Nice. Thanks!
